apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: nginx
spec:
#  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx4
        image: nginx:alpine
        resources:
          requests:
            memory: "50Mi"
            cpu: "0.1"
          limits:
            memory: "50Mi"
            cpu: "0.1"
        ports:
          - containerPort: 80
#      - name: nginx5
#        image: nginx:alpine
#        resources:
#          requests:
#            memory: "50Mi"
#            cpu: "0.1"
#          limits:
#            memory: "50Mi"
#            cpu: "0.1"
#        ports:
#        - containerPort: 81
status: {}